hello-world

diff --git a/8-install-condtions b/8-install-condtions
--- a/8-install-condtions
+++ b/8-install-condtions
@@ -5,4 +5,21 @@ then
   echo "ERROR:: Please run this script with root access"
   exit 1
 fi
+
 yum install mysql -y
+if [ $? -ne 0]
+then 
+   echo  "Installation of mysql is error"
+   exit 1
+else
+   echo   "Installation of mysql is sucess"
+fi
+
+yum install maven -y
+if [ $? -ne 0]
+then 
+   echo  "Installation of maven is error"
+   exit 1
+else  
+   echo  "Installation of maven is error"
+fi
